name: reviewdog
on: [pull_request]
jobs:
  ktlint:
    name: ktlint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          # fail_on_error: true # This causes some weird error, but I'd like to turn it back on
